Mayhem Integration
mayhemheroes/snarkOS pull request #1
Opened 2022-06-29 06:17 UTC by code-terror

## Motivation

(Write your motivation here)

## Test Plan

(Write your test plan here)

## Related PRs

(Link your related PRs here)

2022-07-29 13:58 UTC, xansec requested changes
Please make the requested changes.

2022-07-29 13:58 UTC, xansec commented on Dockerfile
> -FROM ubuntu:18.04 AS builder
Please don't modify upstream Dockerfiles.

2022-07-29 13:58 UTC, xansec commented on Mayhem/deserialization.mayhemfile
> +project: code-terror/snarkos
Please use generic project names.

2022-07-29 13:58 UTC, xansec commented on mayhem.dockerfile
> +# Build Stage
Please don't use git clone.

2022-07-29 19:49 UTC, code-terror commented
@xansec Packaging this repository doesnt work, so using build image for analysis

2022-07-30 05:45 UTC, xansec commented
> Packaging this repository doesnt work
What error are you encountering? I took your existing Dockerfile and installed libssl in the package stage, and it seems to work fine:
```
cat mayhem.dockerfile                                                                                                                                   INT ✘  8s  
# Build Stage
FROM ubuntu:20.04 as builder

## Install build dependencies.
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y cmake clang curl git-all build-essential libssl-dev pkg-config
RUN curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN ${HOME}/.cargo/bin/rustup default nightly
RUN ${HOME}/.cargo/bin/cargo install -f cargo-fuzz
ADD . /snarkOS
WORKDIR /snarkOS/fuzz/
RUN ${HOME}/.cargo/bin/cargo fuzz build
WORKDIR /

FROM ubuntu:20.04
RUN apt-get update && apt-get install -y openssl
RUN mkdir -p /snarkOS/fuzz
COPY --from=builder /snarkOS/fuzz /snarkOS/fuzz
```

Can you try with this approach?

2022-07-30 07:03 UTC, code-terror commented
@xansec Hmm...I was trying with libssl-dev and a bunch of errors were popping up..this approach works..

2022-08-02 05:02 UTC, xansec approved these changes
LGTM!

2022-08-02 05:02 UTC, merged